---
title: "Project Title"
subtitle: "INFO 526 - Summer 2024 - Final Project"
author: 
  - name: "Team name"
    affiliations:
      - name: "School of Information, University of Arizona"
description: "Project description"
format:
   html:
    code-tools: true
    code-overflow: wrap
    embed-resources: true
editor: visual
execute:
  warning: false
  echo: false
---

## Abstract

Add project abstract here.

Introduction:

This project utilizes the dataset from the week of January 23, 2024 on the TidyTuesdayR website. This dataset  focuses on the educational attainment of young people in English towns. Provided by the UK Office for National Statistics, this dataset explores why children and young people in smaller towns often perform better academically than those in larger towns. The data includes a variety of metrics such as population, regional classifications, coastal status, job density, income levels, university presence, and detailed educational outcomes at various stages, from Key Stage 2 through age 22.

I chose to use this dataset because, upon reviewing it, I immediately envisioned the variety of compelling visuals that could be created from the rich and detailed information it contains. The diverse metrics, ranging from educational outcomes to economic factors, present numerous opportunities for insightful data visualizations.

For my analysis with this dataset, I will examine the relationship between university presence and regional differences on the number of 19-year-olds in apprenticeships. This question interests me because it combines educational infrastructure with geographic diversity, potentially revealing how the presence of universities and the specific characteristics of different regions influence the career paths young people choose. My initial thought would be that the absent of a university would push more 19-year-olds into apprenticeships due to the pursing university endeavors is an available option.  

Approach:

To normalize the number of 19-year-olds in apprenticeships relative to the population, I will first sum all the activities at the 19-year age column to find the total population of 19-year-olds. Next, I will calculate the percentage of 19-year-olds in apprenticeships by dividing the number of those in apprenticeships by the total 19-year-old population and multiplying by 100. This percentage will serve as our Y-axis. The X-axis will represent the presence of a university in the town, while the regions will be differentiated by distinct colors to visualize any regional variations effectively. This approach will help identify patterns and differences in apprenticeship participation across various towns and regions, considering both university presence and regional factors. This will be an effective way at looking at the information and designating if the presence of a university has any relationship with 19-year-olds in apprenticeships. The color maps will point out if regions so higher or lower numbers of apprenticeships. 
